spring:
  datasource:
    # &allowMultiQueries=true  允许<delete>中多条删除
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: ${spring.datasource.url}
      driver-class-name: ${spring.datasource.driver-class-name}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      #配置初始化连接数大小
      initial-size: 1
      # 最小连接数
      min-idle: 1
      # 最大连接数
      max-active: 20
      # 配置获取连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位ms
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间，单位ms
      min-evictable-idle-time-millis: 300000
      # 配置连接在池中最小生存时间 ms
      validation-query: SELECT 1 FROM DUAL
      # 是否在连接空闲一段时间后检测器可用性
      test-while-idle: true
      # 是否在获得连接后检测其可用性
      test-on-borrow: true
      # 是否在连接放回连接池后检测器可用性
      test-on-return: false
      # 是否打开 PSCache, oracle 有点用
      pool-prepared-statements: false
      # 并且指定每个连接上 PSCache 的大小
      max-pool-prepared-statement-per-connection-size: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #可以增加访问账号密码【去掉注释就可以】
        # login-username: root
        # login-password: root
        # 禁止重置(点了也没用)
        reset-enable: false

      # 配置监控统计拦截的 filters，去掉后监控界面 sql 无法统计 `wall` 用于防火墙
      filters: stat,wall
      # 配置 webStatFile
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        # 下面看下 https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_%E9%85%8D%E7%BD%AEWebStatFilter
        # session-stat-max-count: 1000
        # principal-session-name: admin
        # principal-cookie-name: admin

        # 配置profileEnable能够监控单个url调用的sql列表。
        profile-enable: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000